### ISSUE TITLE
Reconnect does not trigger in some cases

### ISSUE THREAD

**Issue by amitava82** [hbar-digital/hbar-ws-client#1]
https://github.com/hbar-digital/hbar-ws-client/blob/master/libs/SocketClient.js#L59

Not all the `onerror` events called with error object. For instance, timeout. Should remove the error check and just try reconnect to handle all cases.

**Comment by hbar-digital** [comment]
fixed https://github.com/hbar-digital/hbar-ws-client/commit/516a56e3b33d57997634172b22b0b8ca1310de28

**Comment by amitava82** [comment]
This is causing infinite reconnect loop with error  `InvalidStateError: The connection has not been established yet ` in case of timeout scenario.

**Comment by amitava82** [comment]
Relevant https://github.com/primus/primus/issues/320
